//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/Pumlg.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System.CodeDom.Compiler;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PumlgParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[GeneratedCode("ANTLR", "4.13.1")]
[CLSCompliant(false)]
public interface IPumlgVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.uml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUml([NotNull] PumlgParser.UmlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.class_diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_diagram([NotNull] PumlgParser.Class_diagramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_declaration([NotNull] PumlgParser.Class_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.inheritance_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInheritance_declaration([NotNull] PumlgParser.Inheritance_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.extends_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtends_declaration([NotNull] PumlgParser.Extends_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.implements_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplements_declaration([NotNull] PumlgParser.Implements_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member([NotNull] PumlgParser.Class_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.hide_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHide_declaration([NotNull] PumlgParser.Hide_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] PumlgParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] PumlgParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.connection_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConnection_left([NotNull] PumlgParser.Connection_leftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.connection_right"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConnection_right([NotNull] PumlgParser.Connection_rightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.connection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConnection([NotNull] PumlgParser.ConnectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.multiplicity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicity([NotNull] PumlgParser.MultiplicityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>visibility_public</c>
	/// labeled alternative in <see cref="PumlgParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility_public([NotNull] PumlgParser.Visibility_publicContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>visibility_private</c>
	/// labeled alternative in <see cref="PumlgParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility_private([NotNull] PumlgParser.Visibility_privateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>visibility_protected</c>
	/// labeled alternative in <see cref="PumlgParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility_protected([NotNull] PumlgParser.Visibility_protectedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.function_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_argument([NotNull] PumlgParser.Function_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.function_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_argument_list([NotNull] PumlgParser.Function_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.template_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_argument([NotNull] PumlgParser.Template_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.template_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_argument_list([NotNull] PumlgParser.Template_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.template_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_parameter_list([NotNull] PumlgParser.Template_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.template_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_parameter([NotNull] PumlgParser.Template_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdent([NotNull] PumlgParser.IdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifiers([NotNull] PumlgParser.ModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.stereotype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStereotype([NotNull] PumlgParser.StereotypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>template_type</c>
	/// labeled alternative in <see cref="PumlgParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_type([NotNull] PumlgParser.Template_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>list_type</c>
	/// labeled alternative in <see cref="PumlgParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_type([NotNull] PumlgParser.List_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>generic_list_type</c>
	/// labeled alternative in <see cref="PumlgParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_list_type([NotNull] PumlgParser.Generic_list_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>generic_simple_type</c>
	/// labeled alternative in <see cref="PumlgParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_simple_type([NotNull] PumlgParser.Generic_simple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simple_type</c>
	/// labeled alternative in <see cref="PumlgParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type([NotNull] PumlgParser.Simple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.class_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type([NotNull] PumlgParser.Class_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.item_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem_list([NotNull] PumlgParser.Item_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PumlgParser.enum_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_declaration([NotNull] PumlgParser.Enum_declarationContext context);
}
