@startuml PumlSchemasManager

!theme reddress-darkgreen

package Utils {
    interface IParser {
    ' return png path
    + Parse(source : string) : string
  }

   IParser <|-- Parser
  class Parser {
    + Parse(source : string) : string  
  }
}

package Serializers {
    class Saver {
        + {static} Save(params projects : Projects[])
      }

    class Discoverer {
        + Recursive(folderPath : string) : Project
    }
}


package Data {
  class Schema {
    - {static} Parser { get }  : Parser
    + SourcePath { get ; set } : string

    ' generated on first demand ; can throw errors
    + PngHref { get } : string
  }

   Schema <|-- MergeSchema
  class MergedSchema  {
    + From { get; init; } : string
  }

  class Project {
    + Name { get ; set } : string
    + Schema { get ; set } : Schemas
  }


}

package Commands {
    class Generate {
        + From(sourceFile : string)
    }

    class Merge {
        + From(params schemas : Schema[])
    }

    class Discover {
     ' and save into projects list
        + From(folderPath : string)
    }
}



@enduml
